services:
  - type: web
    name: bmasia-crm
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py createadmin && python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: django-insecure-demo-key-replace-in-production
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SOUNDTRACK_API_TOKEN
        value: YVhId2UyTWJVWEhMRWlycUFPaUl3Y2NtOXNGeUoxR0Q6SVRHazZSWDVYV2FTenhiS1ZwNE1sSmhHUUJEVVRDdDZGU0FwVjZqMXNEQU1EMjRBT2pub2hmZ3NQODRRNndQWg==
      - key: SOUNDTRACK_CLIENT_ID
        value: VCZz6nGt0pkQ1fBsHuO8cqgR6Ctefv7f
      - key: SOUNDTRACK_CLIENT_SECRET
        value: Ht4g6isxxrNXeYgxNkDyfM0TJe508kqJHPdFVihi9KYbOnmfO8v2PipFUCf69zmc