services:
  - type: web
    name: bmasia-crm
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: django-insecure-demo-key-replace-in-production
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SOUNDTRACK_API_TOKEN
        value: your-soundtrack-api-token-here
      - key: SOUNDTRACK_CLIENT_ID
        value: your-soundtrack-client-id-here
      - key: SOUNDTRACK_CLIENT_SECRET
        value: your-soundtrack-client-secret-here