# Generated by Django 5.2.2 on 2025-06-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Contacted', 'Contacted'), ('Quotation Sent', 'Quotation Sent'), ('Contract Sent', 'Contract Sent'), ('Won', 'Won'), ('Lost', 'Lost')], default='Contacted', max_length=50),
        ),
    ]
