# Generated by Django 5.2.2 on 2025-06-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_update_industry_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('Single Location', 'Single Location'), ('Small Chain', 'Small Chain (2-5 locations)'), ('Medium Chain', 'Medium Chain (6-20 locations)'), ('Large Chain', 'Large Chain (21-100 locations)'), ('Major Chain', 'Major Chain (100+ locations)'), ('Franchise', 'Franchise Network')], max_length=20),
        ),
    ]
