# Generated by Django 5.2.2 on 2025-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_add_location_and_zone_tracking'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='crm_app_com_name_38f295_idx',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='zone',
            new_name='region',
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name', 'region'], name='crm_app_com_name_53ec02_idx'),
        ),
    ]
