# Generated by Django 5.2.2 on 2025-06-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_make_body_html_optional'),
    ]

    operations = [
        # First, alter the existing region field to allow null
        migrations.RunSQL(
            "ALTER TABLE crm_app_company ALTER COLUMN region DROP NOT NULL;",
            reverse_sql="ALTER TABLE crm_app_company ALTER COLUMN region SET NOT NULL;"
        ),
    ]
