# Generated by Django 5.2.2 on 2025-06-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_fix_orphaned_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='service_type',
            field=models.CharField(blank=True, choices=[('soundtrack_essential_monthly', 'Soundtrack Essential (Monthly)'), ('soundtrack_essential_yearly', 'Soundtrack Essential (Yearly)'), ('soundtrack_premium_monthly', 'Soundtrack Premium (Monthly)'), ('soundtrack_premium_yearly', 'Soundtrack Premium (Yearly)'), ('soundtrack_enterprise', 'Soundtrack Enterprise (Custom)'), ('custom_package', 'Custom Package'), ('one_time_setup', 'One-time Setup'), ('consulting', 'Consulting Services'), ('maintenance', 'Maintenance & Support')], help_text='Specific service or plan', max_length=50),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
