# Generated by Django 5.2.2 on 2025-06-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_simplify_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='service_type',
            field=models.CharField(blank=True, choices=[('soundtrack_essential_monthly', 'Soundtrack Essential (Monthly)'), ('soundtrack_essential_yearly', 'Soundtrack Essential (Yearly)'), ('soundtrack_unlimited_monthly', 'Soundtrack Unlimited (Monthly)'), ('soundtrack_unlimited_yearly', 'Soundtrack Unlimited (Yearly)'), ('soundtrack_enterprise', 'Soundtrack Enterprise (Custom)'), ('beat_breeze_monthly', 'Beat Breeze (Monthly)'), ('beat_breeze_yearly', 'Beat Breeze (Yearly)'), ('custom_package', 'Custom Package'), ('one_time_setup', 'One-time Setup'), ('consulting', 'Consulting Services'), ('maintenance', 'Maintenance & Support')], help_text='Specific service or plan', max_length=50),
        ),
    ]
