# Generated by Django 5.2.2 on 2025-10-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_alter_company_country_alter_emaillog_email_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_entity',
            field=models.CharField(choices=[('BMAsia Limited', 'BMAsia Limited (Hong Kong)'), ('BMAsia (Thailand) Co., Ltd.', 'BMAsia (Thailand) Co., Ltd.')], default='BMAsia Limited', help_text='Legal entity for billing and invoicing', max_length=50),
        ),
    ]
