# Generated by Django 5.2.2 on 2025-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_company_billing_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_entity_name',
            field=models.CharField(blank=True, help_text='Legal registered company name (if different from display name)', max_length=255),
        ),
    ]
