# Generated by Django 5.2.2 on 2025-10-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_add_legal_entity_name_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='Gmail address for sending emails (e.g., user@bmasiamusic.com)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Gmail app password (will be encrypted)', max_length=255, null=True),
        ),
    ]
