# Generated by Django 5.2.2 on 2025-10-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_add_legal_entity_name_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(blank=True, help_text='Optional HTML email body. Leave blank to auto-generate from text body. Available variables: {{company_name}}, {{contact_name}}, {{document_number}}, {{amount}}, {{valid_until}}, {{days_until_expiry}}, {{zone_name}}, {{subscription_expiry}}'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(help_text='Plain text email body. Available variables: {{company_name}}, {{contact_name}}, {{document_number}}, {{amount}}, {{valid_until}}, {{days_until_expiry}}, {{zone_name}}, {{subscription_expiry}}'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this template'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Descriptive name for this email template', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Available variables: {{company_name}}, {{contact_name}}, {{document_number}}, {{amount}}, {{valid_until}}, {{days_until_expiry}}', max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('quote_send', 'Send Quote'), ('contract_send', 'Send Contract'), ('invoice_send', 'Send Invoice'), ('renewal_30_days', '30-Day Renewal Reminder'), ('renewal_14_days', '14-Day Renewal Reminder'), ('renewal_7_days', '7-Day Renewal Reminder'), ('renewal_urgent', 'Urgent Renewal Notice'), ('renewal_manual', 'Manual Renewal Reminder'), ('invoice_new', 'New Invoice'), ('payment_reminder_7_days', '7-Day Payment Reminder'), ('payment_reminder_14_days', '14-Day Payment Reminder'), ('payment_overdue', 'Payment Overdue Notice'), ('quarterly_checkin', 'Quarterly Check-in'), ('seasonal_christmas', 'Christmas Season Preparation'), ('seasonal_newyear', 'Chinese New Year Preparation'), ('seasonal_songkran', 'Songkran Preparation'), ('seasonal_ramadan', 'Ramadan Preparation'), ('zone_offline_48h', 'Zone Offline 48 Hours'), ('zone_offline_7d', 'Zone Offline 7 Days'), ('welcome', 'Welcome Email'), ('contract_signed', 'Contract Signed Confirmation')], help_text='Type of email this template is used for', max_length=50, unique=True),
        ),
    ]
