# Generated by Django 5.2.2 on 2025-11-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_alter_emailtemplate_body_html_and_more'),
        ('crm_app', '0025_user_smtp_email_user_smtp_password'),
    ]

    operations = [
    ]
