# Generated by Django 5.2.2 on 2025-11-14 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models, connection


def safe_rename_campaign_table(apps, schema_editor):
    """
    Safely rename the campaign table if it exists.
    If the table doesn't exist, create it with the new name.
    """
    with connection.cursor() as cursor:
        # Check if new table already exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'crm_app_email_campaign'
            )
        """)
        new_exists = cursor.fetchone()[0]

        if new_exists:
            print("✓ Table crm_app_email_campaign already exists")
            return

        # Check if old table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'crm_app_emailcampaign'
            )
        """)
        old_exists = cursor.fetchone()[0]

        if old_exists:
            print("Renaming crm_app_emailcampaign to crm_app_email_campaign")
            cursor.execute("ALTER TABLE crm_app_emailcampaign RENAME TO crm_app_email_campaign")
        else:
            print("Neither table exists - table will be created by subsequent operations")


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026a_create_campaign_table_if_missing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed')], default='pending', help_text='Current status of this campaign recipient', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When email was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When email was delivered', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='First time email was opened', null=True)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='First time link was clicked', null=True)),
                ('bounced_at', models.DateTimeField(blank=True, help_text='When email bounced', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When sending failed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed')),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
                'verbose_name_plural': 'Campaign Recipients',
                'db_table': 'crm_app_campaign_recipient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Campaign', 'verbose_name_plural': 'Email Campaigns'},
        ),
        migrations.RemoveIndex(
            model_name='emailcampaign',
            name='crm_app_ema_campaig_7e3b89_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='crm_app_ema_company_99dbe1_idx',
            old_name='crm_app_ema_company_c5ff78_idx',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='actual_send_date',
            field=models.DateTimeField(blank=True, help_text='When campaign was actually sent', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='audience_count',
            field=models.IntegerField(default=0, help_text='Cached count of recipients (auto-updated)'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text='Reply-to email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_send_date',
            field=models.DateTimeField(blank=True, help_text='When to send this campaign', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='send_immediately',
            field=models.BooleanField(default=False, help_text="Send as soon as status is changed to 'sending'"),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Email address to send from (leave blank to use default)', max_length=254),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Email subject line', max_length=200),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='target_audience',
            field=models.JSONField(blank=True, help_text='Segmentation criteria e.g. {"industry": "Hotels", "country": "Thailand", "contact_type": "Primary"}', null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional: Use existing template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='crm_app.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_bounced',
            field=models.IntegerField(default=0, help_text='Bounced emails'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_clicked',
            field=models.IntegerField(default=0, help_text='Unique clicks'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_complained',
            field=models.IntegerField(default=0, help_text='Marked as spam'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_delivered',
            field=models.IntegerField(default=0, help_text='Successfully delivered'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_opened',
            field=models.IntegerField(default=0, help_text='Unique opens'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_sent',
            field=models.IntegerField(default=0, help_text='Total emails sent'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_unsubscribed',
            field=models.IntegerField(default=0, help_text='Unsubscribed from this campaign'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('renewal_sequence', 'Renewal Reminder Sequence'), ('payment_sequence', 'Payment Reminder Sequence'), ('seasonal', 'Seasonal Campaign'), ('quarterly', 'Quarterly Check-in'), ('custom', 'Custom Campaign'), ('newsletter', 'Newsletter'), ('promotion', 'Promotional Campaign'), ('onboarding', 'Onboarding Sequence'), ('engagement', 'Engagement Campaign')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific company for single-company campaigns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='crm_app.company'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='name',
            field=models.CharField(help_text='Campaign name for internal tracking', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(blank=True, help_text='HTML email body. Use variables like {{company_name}}, {{contact_name}}, {{days_until_expiry}}'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(help_text='Plain text email body for non-HTML clients'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('renewal_30_days', '30-Day Renewal Reminder'), ('renewal_14_days', '14-Day Renewal Reminder'), ('renewal_7_days', '7-Day Renewal Reminder'), ('renewal_urgent', 'Urgent Renewal Notice'), ('invoice_new', 'New Invoice'), ('payment_reminder_7_days', '7-Day Payment Reminder'), ('payment_reminder_14_days', '14-Day Payment Reminder'), ('payment_overdue', 'Payment Overdue Notice'), ('quarterly_checkin', 'Quarterly Check-in'), ('seasonal_christmas', 'Christmas Season Preparation'), ('seasonal_newyear', 'Chinese New Year Preparation'), ('seasonal_songkran', 'Songkran Preparation'), ('seasonal_ramadan', 'Ramadan Preparation'), ('zone_offline_48h', 'Zone Offline 48 Hours'), ('zone_offline_7d', 'Zone Offline 7 Days'), ('welcome', 'Welcome Email'), ('contract_signed', 'Contract Signed Confirmation')], max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status', '-created_at'], name='crm_app_ema_status_e2260a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['campaign_type', 'status'], name='crm_app_ema_campaig_62ea85_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['scheduled_send_date', 'status'], name='crm_app_ema_schedul_fd708b_idx'),
        ),
        migrations.RunPython(safe_rename_campaign_table, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='campaignrecipient',
            name='campaign',
            field=models.ForeignKey(help_text='Email campaign this recipient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='crm_app.emailcampaign'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='contact',
            field=models.ForeignKey(help_text='Contact receiving the campaign email', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_receipts', to='crm_app.contact'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='email_log',
            field=models.ForeignKey(blank=True, help_text='Link to the actual email sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipient', to='crm_app.emaillog'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='crm_app_cam_campaig_aa9c80_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['contact', 'status'], name='crm_app_cam_contact_d8416a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['sent_at'], name='crm_app_cam_sent_at_684219_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['status', '-sent_at'], name='crm_app_cam_status_34ee28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'contact')},
        ),
    ]
