# Generated by Django 5.2.2 on 2025-11-18 02:41
# This is a state-only migration - the table was already renamed by migration 0027's RunPython operation

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_campaignrecipient_alter_emailcampaign_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='emailcampaign',
                    table='crm_app_email_campaign',
                ),
            ],
            database_operations=[
                # No database changes needed - table already renamed by migration 0027
            ],
        ),
    ]
