# Generated by Django 5.2.2 on 2025-11-18 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0028_alter_emailcampaign_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'New Customer Onboarding'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this sequence does')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Sequence',
                'verbose_name_plural': 'Email Sequences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='When enrolled')),
                ('started_at', models.DateTimeField(blank=True, help_text='When first email sent', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When all steps done', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=20)),
                ('current_step_number', models.PositiveIntegerField(default=1, help_text='Which step is next')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='crm_app.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='crm_app.contact')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm_app.emailsequence')),
            ],
            options={
                'verbose_name': 'Sequence Enrollment',
                'verbose_name_plural': 'Sequence Enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(help_text='Order in sequence (1, 2, 3...)')),
                ('name', models.CharField(help_text="e.g., 'Welcome Email', 'Day 3 Tips'", max_length=200)),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Send X days after previous step (or enrollment for step 1)')),
                ('is_active', models.BooleanField(default=True)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_steps', to='crm_app.emailtemplate')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm_app.emailsequence')),
            ],
            options={
                'verbose_name': 'Sequence Step',
                'verbose_name_plural': 'Sequence Steps',
                'ordering': ['sequence', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStepExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField(help_text='When this step should be sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When actually sent', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_executions', to='crm_app.emaillog')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='crm_app.sequenceenrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='crm_app.sequencestep')),
            ],
            options={
                'verbose_name': 'Step Execution',
                'verbose_name_plural': 'Step Executions',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='sequenceenrollment',
            index=models.Index(fields=['status', '-enrolled_at'], name='crm_app_seq_status_5e3f23_idx'),
        ),
        migrations.AddIndex(
            model_name='sequenceenrollment',
            index=models.Index(fields=['sequence', 'status'], name='crm_app_seq_sequenc_43cef1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequenceenrollment',
            unique_together={('sequence', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='sequencestep',
            unique_together={('sequence', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='sequencestepexecution',
            index=models.Index(fields=['status', 'scheduled_for'], name='crm_app_seq_status_0a0a14_idx'),
        ),
        migrations.AddIndex(
            model_name='sequencestepexecution',
            index=models.Index(fields=['enrollment', 'status'], name='crm_app_seq_enrollm_7164e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencestepexecution',
            unique_together={('enrollment', 'step')},
        ),
    ]
