# Generated by Django 5.2.2 on 2025-11-19 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_emailsequence_sequenceenrollment_sequencestep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Segment name (e.g., 'High-Value Hotels in Thailand')", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this segment represents')),
                ('segment_type', models.CharField(choices=[('dynamic', 'Dynamic - Auto-updates based on rules'), ('static', 'Static - Manually curated list')], default='dynamic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('filter_criteria', models.JSONField(blank=True, default=dict, help_text='Dynamic filter rules in JSON format')),
                ('member_count', models.IntegerField(default=0, help_text='Cached count of members (auto-updated)')),
                ('last_calculated_at', models.DateTimeField(blank=True, help_text='When member count was last recalculated', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for organization', max_length=500)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this segment was last used in a campaign', null=True)),
                ('times_used', models.IntegerField(default=0, help_text='How many times used in campaigns/sequences')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_segments', to=settings.AUTH_USER_MODEL)),
                ('static_companies', models.ManyToManyField(blank=True, help_text='Manually selected companies (for static segments)', related_name='segments', to='crm_app.company')),
                ('static_contacts', models.ManyToManyField(blank=True, help_text='Manually selected contacts (for static segments)', related_name='segments', to='crm_app.contact')),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='crm_app_cus_status_22b6f8_idx'), models.Index(fields=['segment_type', 'status'], name='crm_app_cus_segment_ce31ea_idx'), models.Index(fields=['created_by', 'status'], name='crm_app_cus_created_129e97_idx')],
            },
        ),
    ]
