# Generated by Django 5.2.2 on 2025-11-19 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0030_customer_segments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, help_text='Auto-generated ticket number (T-YYYYMMDD-NNNN)', max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending', 'Pending Customer Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('category', models.CharField(choices=[('technical', 'Technical Issue'), ('billing', 'Billing Question'), ('zone_config', 'Zone Configuration'), ('account', 'Account Management'), ('feature_request', 'Feature Request'), ('general', 'General Inquiry')], default='general', max_length=20)),
                ('assigned_team', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Finance', 'Finance'), ('Tech', 'Tech Support'), ('Music', 'Music Design'), ('Admin', 'Admin')], help_text='Team responsible for this ticket', max_length=20)),
                ('first_response_at', models.DateTimeField(blank=True, help_text='When first comment/response was added', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When ticket was marked as resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When ticket was closed', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='When ticket should be resolved by', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to handle this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Company this ticket is for', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm_app.company')),
                ('contact', models.ForeignKey(blank=True, help_text='Contact who submitted the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm_app.contact')),
                ('created_by', models.ForeignKey(help_text='User who created this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Upload file', upload_to='tickets/attachments/%Y/%m/')),
                ('name', models.CharField(help_text='File name', max_length=200)),
                ('size', models.IntegerField(help_text='File size in bytes')),
                ('ticket', models.ForeignKey(help_text='Ticket this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm_app.ticket')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Comment text')),
                ('is_internal', models.BooleanField(default=False, help_text='True for internal notes, False for public comments')),
                ('author', models.ForeignKey(help_text='User who wrote this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm_app.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'status'], name='crm_app_tic_company_1b28dc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_app_tic_assigne_1bf4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'status'], name='crm_app_tic_priorit_d1f22d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category', 'status'], name='crm_app_tic_categor_0bebea_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at'], name='crm_app_tic_created_0d2419_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', 'created_at'], name='crm_app_tic_ticket__340e27_idx'),
        ),
    ]
