# Generated by Django 5.2.2 on 2025-11-19 14:24

import django.contrib.postgres.search
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_ticket_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly slug (auto-generated)', unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI display (e.g., #3B82F6)', max_length=7)),
            ],
            options={
                'verbose_name': 'KB Tag',
                'verbose_name_plural': 'KB Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KBCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly slug (auto-generated)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'wrench', 'dollar-sign', 'music') for UI display", max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying categories (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is visible')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category (null for top-level categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm_app.kbcategory')),
            ],
            options={
                'verbose_name': 'KB Category',
                'verbose_name_plural': 'KB Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated article number (KB-YYYYMMDD-NNNN)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Article title', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly slug (auto-generated from title)', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Main article content (supports HTML)')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary/preview (optional, auto-generated from content if empty)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Publication status', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public - Visible to customers'), ('internal', 'Internal - Only visible to staff')], default='internal', help_text='Who can view this article', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Feature this article on KB homepage')),
                ('view_count', models.IntegerField(default=0, editable=False, help_text='Total views')),
                ('helpful_count', models.IntegerField(default=0, editable=False, help_text="Number of 'helpful' votes")),
                ('not_helpful_count', models.IntegerField(default=0, editable=False, help_text="Number of 'not helpful' votes")),
                ('published_at', models.DateTimeField(blank=True, help_text='When article was published', null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('author', models.ForeignKey(help_text='Article author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Primary category for this article', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='crm_app.kbcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for flexible categorization', related_name='articles', to='crm_app.kbtag')),
            ],
            options={
                'verbose_name': 'KB Article',
                'verbose_name_plural': 'KB Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketKBArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text='Was this article helpful for resolving the ticket? (optional)', null=True)),
                ('article', models.ForeignKey(help_text='KB article linked to this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='linked_tickets', to='crm_app.kbarticle')),
                ('linked_by', models.ForeignKey(help_text='User who linked this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_kb_links', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Support ticket', on_delete=django.db.models.deletion.CASCADE, related_name='kb_articles', to='crm_app.ticket')),
            ],
            options={
                'verbose_name': 'Ticket KB Article Link',
                'verbose_name_plural': 'Ticket KB Article Links',
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='KBArticleAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Attachment file', upload_to='kb_attachments/%Y/%m/')),
                ('filename', models.CharField(help_text='Original filename', max_length=200)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(help_text='Article this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm_app.kbarticle')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KB Article Attachment',
                'verbose_name_plural': 'KB Article Attachments',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['article', '-uploaded_at'], name='crm_app_kba_article_360322_idx')],
            },
        ),
        migrations.CreateModel(
            name='KBArticleRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(help_text='True = Helpful, False = Not Helpful')),
                ('article', models.ForeignKey(help_text='Article being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='crm_app.kbarticle')),
                ('user', models.ForeignKey(help_text='User who voted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_article_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KB Article Rating',
                'verbose_name_plural': 'KB Article Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'is_helpful'], name='crm_app_kba_article_6beb9f_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='KBArticleRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('related', 'Related Article'), ('see_also', 'See Also'), ('prerequisite', 'Prerequisite Reading')], default='related', help_text='Type of relationship', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying related articles')),
                ('from_article', models.ForeignKey(help_text='Source article', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='crm_app.kbarticle')),
                ('to_article', models.ForeignKey(help_text='Related article', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='crm_app.kbarticle')),
            ],
            options={
                'verbose_name': 'KB Article Relation',
                'verbose_name_plural': 'KB Article Relations',
                'ordering': ['from_article', 'display_order'],
                'indexes': [models.Index(fields=['from_article', 'relation_type'], name='crm_app_kba_from_ar_a704f7_idx')],
                'unique_together': {('from_article', 'to_article')},
            },
        ),
        migrations.CreateModel(
            name='KBArticleView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of viewer', null=True)),
                ('session_id', models.CharField(help_text='Session ID to prevent duplicate counting', max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(help_text='Article that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='crm_app.kbarticle')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_article_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KB Article View',
                'verbose_name_plural': 'KB Article Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['article', '-viewed_at'], name='crm_app_kba_article_263f4b_idx'), models.Index(fields=['user', '-viewed_at'], name='crm_app_kba_user_id_f47fb1_idx')],
                'unique_together': {('article', 'session_id')},
            },
        ),
        migrations.AddIndex(
            model_name='kbcategory',
            index=models.Index(fields=['parent', 'is_active'], name='crm_app_kbc_parent__aabbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='kbcategory',
            index=models.Index(fields=['display_order', 'name'], name='crm_app_kbc_display_2ea448_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['status', 'visibility'], name='crm_app_kba_status_bcedcc_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['category', 'status'], name='crm_app_kba_categor_b1058b_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['featured', 'status'], name='crm_app_kba_feature_6b6c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['-published_at'], name='crm_app_kba_publish_f7e193_idx'),
        ),
        migrations.AddIndex(
            model_name='kbarticle',
            index=models.Index(fields=['article_number'], name='crm_app_kba_article_a6a099_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketkbarticle',
            index=models.Index(fields=['ticket', '-linked_at'], name='crm_app_tic_ticket__4bcae0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketkbarticle',
            index=models.Index(fields=['article', '-linked_at'], name='crm_app_tic_article_b71408_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketkbarticle',
            unique_together={('ticket', 'article')},
        ),
        # Add GIN index for PostgreSQL full-text search on KBArticle.search_vector
        migrations.AddIndex(
            model_name='kbarticle',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='crm_app_kba_search_gin_idx'
            ),
        ),
    ]
