# Generated by Django 5.2.2 on 2025-11-21 06:41

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0032_knowledge_base_phase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('remote_username', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('remote_password', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('setup_details', models.TextField(blank=True, help_text='Setup and configuration details')),
                ('notes', models.TextField(blank=True, help_text='Equipment-specific notes: past issues, troubleshooting history')),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('installed', 'Installed'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('upgrade', 'Upgrade'), ('replaced', 'Replaced'), ('retired', 'Retired'), ('note', 'Note Added')], max_length=20)),
                ('description', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipment History',
                'verbose_name_plural': 'Equipment History',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='computer', help_text='Material-UI icon name (e.g., computer, tablet, speaker)', max_length=50)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='kbarticle',
            name='crm_app_kba_search_gin_idx',
        ),
        migrations.AddField(
            model_name='company',
            name='it_notes',
            field=models.TextField(blank=True, help_text='General IT notes: remote access details, contact preferences, configurations'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='crm_app.company'),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm_app.equipment'),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='crm_app.equipmenttype'),
        ),
    ]
