# Generated by Django 5.2.2 on 2025-11-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0033_equipment_equipmenthistory_equipmenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Location/zone where this equipment is installed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='crm_app.zone'),
        ),
    ]
