# Generated by Django 5.2.2 on 2025-11-25 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0034_equipment_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('no_device', 'No Device Paired'), ('expired', 'Subscription Expired'), ('pending', 'Pending Activation'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Date when zone was added to this contract (typically contract start_date)')),
                ('end_date', models.DateField(blank=True, help_text='Date when zone was removed from this contract (null = currently active)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this zone is currently covered by this contract')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this zone-contract relationship')),
                ('contract', models.ForeignKey(help_text='Contract covering this zone', on_delete=django.db.models.deletion.CASCADE, related_name='contract_zones', to='crm_app.contract')),
                ('zone', models.ForeignKey(help_text='Zone covered by this contract', on_delete=django.db.models.deletion.PROTECT, related_name='zone_contracts', to='crm_app.zone')),
            ],
            options={
                'ordering': ['-start_date', 'zone__name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Music zones covered by this contract', related_name='contracts', through='crm_app.ContractZone', to='crm_app.zone'),
        ),
        migrations.AddIndex(
            model_name='contractzone',
            index=models.Index(fields=['contract', 'is_active'], name='crm_app_con_contrac_9b7800_idx'),
        ),
        migrations.AddIndex(
            model_name='contractzone',
            index=models.Index(fields=['zone', 'is_active'], name='crm_app_con_zone_id_2c2a68_idx'),
        ),
        migrations.AddIndex(
            model_name='contractzone',
            index=models.Index(fields=['start_date', 'end_date'], name='crm_app_con_start_d_929ae0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractzone',
            unique_together={('contract', 'zone', 'start_date')},
        ),
    ]
