# Generated by Django 5.2.2 on 2025-11-25 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0035_add_contract_zone_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Device name (e.g., 'Lobby PC', 'Restaurant Tablet')", max_length=100)),
                ('device_type', models.CharField(choices=[('pc', 'PC / Computer'), ('tablet', 'Tablet'), ('music_player', 'Music Player Box'), ('other', 'Other')], default='pc', max_length=20)),
                ('model_info', models.CharField(blank=True, help_text='Optional: Model name, serial number, or other identifier', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Tech support notes about this device')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='crm_app.company')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Physical device running this zone (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='crm_app.device'),
        ),
    ]
