# Generated by Django 5.2.2 on 2025-11-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0036_add_device_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='equipmenthistory',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmenthistory',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='EquipmentHistory',
        ),
    ]
