# Generated by Django 5.2.2 on 2025-11-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0037_remove_equipment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsequence',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='System default automations created during setup'),
        ),
        migrations.AddField(
            model_name='emailsequence',
            name='sequence_type',
            field=models.CharField(choices=[('manual', 'Manual Enrollment'), ('auto_renewal', 'Auto: Contract Renewal'), ('auto_payment', 'Auto: Payment Reminders'), ('auto_quarterly', 'Auto: Quarterly Check-ins')], default='manual', help_text='Type of automation - manual requires enrollment, auto types trigger automatically', max_length=20),
        ),
        migrations.AddField(
            model_name='emailsequence',
            name='trigger_days_before',
            field=models.IntegerField(blank=True, help_text='For auto types: days before/after event to trigger (e.g., 30 for 30 days before contract expiry)', null=True),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='enrollment_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto_trigger', 'Auto Trigger')], default='manual', help_text='How this enrollment was created', max_length=20),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='trigger_entity_id',
            field=models.UUIDField(blank=True, help_text='ID of the triggering entity for deduplication', null=True),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='trigger_entity_type',
            field=models.CharField(blank=True, help_text='Type of entity that triggered enrollment: contract, invoice, company', max_length=50, null=True),
        ),
    ]
