# Generated by Django Admin Expert for BMAsia CRM

from django.db import migrations


def create_default_automations(apps, schema_editor):
    """Create default system automation sequences."""
    EmailSequence = apps.get_model('crm_app', 'EmailSequence')
    EmailSequenceStep = apps.get_model('crm_app', 'EmailSequenceStep')
    EmailTemplate = apps.get_model('crm_app', 'EmailTemplate')

    # Helper to get template by type (gracefully handles missing templates)
    def get_template(template_type):
        try:
            return EmailTemplate.objects.filter(
                template_type=template_type,
                is_active=True
            ).first()
        except EmailTemplate.DoesNotExist:
            return None

    # 1. Contract Renewal Reminders Automation
    renewal_seq = EmailSequence.objects.create(
        name='Contract Renewal Reminders',
        description='Automatic reminders sent before contract expiry dates. Emails are sent at 30, 14, 7, and 2 days before expiration. Customize timing and templates in the Email Automations section.',
        sequence_type='auto_renewal',
        status='active',
        is_system_default=True,
    )

    # Renewal sequence steps
    renewal_steps = [
        {
            'step_order': 1,
            'days_delay': -30,  # 30 days before
            'send_time': '09:00:00',
            'template_type': 'renewal_30_days',
            'subject': 'Contract Renewal - 30 Days Notice',
        },
        {
            'step_order': 2,
            'days_delay': -14,  # 14 days before
            'send_time': '09:00:00',
            'template_type': 'renewal_14_days',
            'subject': 'Contract Renewal - 14 Days Notice',
        },
        {
            'step_order': 3,
            'days_delay': -7,  # 7 days before
            'send_time': '09:00:00',
            'template_type': 'renewal_7_days',
            'subject': 'Contract Renewal - 7 Days Notice',
        },
        {
            'step_order': 4,
            'days_delay': -2,  # 2 days before
            'send_time': '09:00:00',
            'template_type': 'renewal_urgent',
            'subject': 'Urgent: Contract Expiring in 2 Days',
        },
    ]

    for step_data in renewal_steps:
        template = get_template(step_data['template_type'])
        EmailSequenceStep.objects.create(
            sequence=renewal_seq,
            step_order=step_data['step_order'],
            days_delay=step_data['days_delay'],
            send_time=step_data['send_time'],
            email_template=template,
            subject=step_data['subject'],
        )

    # 2. Payment Reminders Automation
    payment_seq = EmailSequence.objects.create(
        name='Payment Reminders',
        description='Automatic reminders for overdue invoices. Emails are sent at 7, 14, and 21+ days after invoice due date. Customize timing and templates in the Email Automations section.',
        sequence_type='auto_payment',
        status='active',
        is_system_default=True,
    )

    payment_steps = [
        {
            'step_order': 1,
            'days_delay': 7,  # 7 days after due date
            'send_time': '10:00:00',
            'template_type': 'payment_reminder_7_days',
            'subject': 'Payment Reminder - 7 Days Overdue',
        },
        {
            'step_order': 2,
            'days_delay': 14,  # 14 days after due date
            'send_time': '10:00:00',
            'template_type': 'payment_reminder_14_days',
            'subject': 'Payment Reminder - 14 Days Overdue',
        },
        {
            'step_order': 3,
            'days_delay': 21,  # 21 days after due date
            'send_time': '10:00:00',
            'template_type': 'payment_overdue',
            'subject': 'Urgent: Payment 21+ Days Overdue',
        },
    ]

    for step_data in payment_steps:
        template = get_template(step_data['template_type'])
        EmailSequenceStep.objects.create(
            sequence=payment_seq,
            step_order=step_data['step_order'],
            days_delay=step_data['days_delay'],
            send_time=step_data['send_time'],
            email_template=template,
            subject=step_data['subject'],
        )

    # 3. Quarterly Check-ins Automation
    quarterly_seq = EmailSequence.objects.create(
        name='Quarterly Check-ins',
        description='Automatic check-in emails sent every 90 days to active customers. Helps maintain relationships and gather feedback. Customize the template in the Email Automations section.',
        sequence_type='auto_quarterly',
        status='active',
        is_system_default=True,
    )

    quarterly_template = get_template('quarterly_checkin')
    EmailSequenceStep.objects.create(
        sequence=quarterly_seq,
        step_order=1,
        days_delay=0,
        send_time='14:00:00',  # 2 PM
        email_template=quarterly_template,
        subject='Quarterly Check-in - How Are We Doing?',
    )


def remove_default_automations(apps, schema_editor):
    """Remove default system automations (reverse migration)."""
    EmailSequence = apps.get_model('crm_app', 'EmailSequence')
    # Only delete system defaults to preserve user-created sequences
    EmailSequence.objects.filter(is_system_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0038_add_sequence_types_and_enrollment_source'),
    ]

    operations = [
        migrations.RunPython(
            create_default_automations,
            remove_default_automations,
        ),
    ]
