# Generated by Django Admin Expert for BMAsia CRM

from django.db import migrations


def create_default_automations(apps, schema_editor):
    """Create default system automation sequences."""
    EmailSequence = apps.get_model('crm_app', 'EmailSequence')
    SequenceStep = apps.get_model('crm_app', 'SequenceStep')
    EmailTemplate = apps.get_model('crm_app', 'EmailTemplate')

    # Helper to get template by type (gracefully handles missing templates)
    def get_template(template_type):
        try:
            return EmailTemplate.objects.filter(
                template_type=template_type,
                is_active=True
            ).first()
        except:
            return None

    # Get a default template to use if specific one doesn't exist
    def get_default_template():
        return EmailTemplate.objects.first()

    # 1. Contract Renewal Reminders Automation
    renewal_seq = EmailSequence.objects.create(
        name='Contract Renewal Reminders',
        description='Automatic reminders sent before contract expiry dates. Emails are sent at 30, 14, 7, and 2 days before expiration. Customize timing and templates in the Email Automations section.',
        sequence_type='auto_renewal',
        status='active',
        is_system_default=True,
    )

    # Renewal sequence steps - delay_days represents days BEFORE the trigger
    # Step 1 fires first (30 days before), then step 2 (14 days before), etc.
    renewal_steps = [
        {'step_number': 1, 'delay_days': 30, 'name': '30-Day Reminder', 'template_type': 'renewal_30_days'},
        {'step_number': 2, 'delay_days': 14, 'name': '14-Day Reminder', 'template_type': 'renewal_14_days'},
        {'step_number': 3, 'delay_days': 7, 'name': '7-Day Reminder', 'template_type': 'renewal_7_days'},
        {'step_number': 4, 'delay_days': 2, 'name': 'Urgent Reminder', 'template_type': 'renewal_urgent'},
    ]

    default_template = get_default_template()
    for step_data in renewal_steps:
        template = get_template(step_data['template_type']) or default_template
        if template:
            SequenceStep.objects.create(
                sequence=renewal_seq,
                step_number=step_data['step_number'],
                name=step_data['name'],
                delay_days=step_data['delay_days'],
                email_template=template,
                is_active=True,
            )

    # 2. Payment Reminders Automation
    payment_seq = EmailSequence.objects.create(
        name='Payment Reminders',
        description='Automatic reminders for overdue invoices. Emails are sent at 7, 14, and 21+ days after invoice due date. Customize timing and templates in the Email Automations section.',
        sequence_type='auto_payment',
        status='active',
        is_system_default=True,
    )

    payment_steps = [
        {'step_number': 1, 'delay_days': 7, 'name': '7 Days Overdue', 'template_type': 'payment_reminder_7_days'},
        {'step_number': 2, 'delay_days': 14, 'name': '14 Days Overdue', 'template_type': 'payment_reminder_14_days'},
        {'step_number': 3, 'delay_days': 21, 'name': '21+ Days Overdue', 'template_type': 'payment_overdue'},
    ]

    for step_data in payment_steps:
        template = get_template(step_data['template_type']) or default_template
        if template:
            SequenceStep.objects.create(
                sequence=payment_seq,
                step_number=step_data['step_number'],
                name=step_data['name'],
                delay_days=step_data['delay_days'],
                email_template=template,
                is_active=True,
            )

    # 3. Quarterly Check-ins Automation
    quarterly_seq = EmailSequence.objects.create(
        name='Quarterly Check-ins',
        description='Automatic check-in emails sent every 90 days to active customers. Helps maintain relationships and gather feedback. Customize the template in the Email Automations section.',
        sequence_type='auto_quarterly',
        status='active',
        is_system_default=True,
    )

    quarterly_template = get_template('quarterly_checkin') or default_template
    if quarterly_template:
        SequenceStep.objects.create(
            sequence=quarterly_seq,
            step_number=1,
            name='Quarterly Check-in',
            delay_days=0,
            email_template=quarterly_template,
            is_active=True,
        )


def remove_default_automations(apps, schema_editor):
    """Remove default system automations (reverse migration)."""
    EmailSequence = apps.get_model('crm_app', 'EmailSequence')
    # Only delete system defaults to preserve user-created sequences
    EmailSequence.objects.filter(is_system_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0038_add_sequence_types_and_enrollment_source'),
    ]

    operations = [
        migrations.RunPython(
            create_default_automations,
            remove_default_automations,
        ),
    ]
