# Generated by Django 5.2.2 on 2025-12-13 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0039_create_default_automations'),
    ]

    operations = [
        # Add Company corporate structure fields
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(
                blank=True,
                help_text='Corporate parent company (e.g., Hilton Corporate)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_companies',
                to='crm_app.company'
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='is_corporate_parent',
            field=models.BooleanField(
                default=False,
                help_text='True if this is a corporate HQ that manages multiple venues'
            ),
        ),
        
        # Add Contract corporate contract fields
        migrations.AddField(
            model_name='contract',
            name='contract_category',
            field=models.CharField(
                choices=[
                    ('standard', 'Standard Contract'),
                    ('corporate_master', 'Corporate Master Agreement'),
                    ('participation', 'Participation Agreement')
                ],
                default='standard',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='master_contract',
            field=models.ForeignKey(
                blank=True,
                help_text='Reference to master agreement (for participation agreements)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='participation_agreements',
                to='crm_app.contract'
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_signatory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_signatory_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='bmasia_signatory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='bmasia_signatory_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_terms',
            field=models.TextField(
                blank=True,
                help_text='Custom terms for master agreements'
            ),
        ),
        
        # Create StaticDocument model
        migrations.CreateModel(
            name='StaticDocument',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(
                    choices=[
                        ('standard_terms_th', 'Standard Terms - Thailand/Hong Kong'),
                        ('standard_terms_intl', 'Standard Terms - International')
                    ],
                    max_length=50,
                    unique=True
                )),
                ('file', models.FileField(upload_to='static_documents/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Document',
                'verbose_name_plural': 'Static Documents',
                'ordering': ['-created_at'],
            },
        ),
        
    ]
