# Generated by Django 5.2.2 on 2025-12-16 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0040_add_corporate_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('preamble', 'Preamble/Introduction'), ('service_standard', 'Service Package - Standard'), ('service_managed', 'Service Package - Managed'), ('service_custom', 'Service Package - Custom'), ('payment_thailand', 'Payment Terms - Thailand'), ('payment_international', 'Payment Terms - International'), ('activation', 'Activation Terms')], max_length=30)),
                ('content', models.TextField(help_text='Template text with {{variables}} for substitution')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-select for new contracts')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Full description of this service item')),
                ('is_standard', models.BooleanField(default=True, help_text='Show in selector for new contracts')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Package Item',
                'verbose_name_plural': 'Service Package Items',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='activation_custom',
            field=models.TextField(blank=True, help_text='Custom activation terms (overrides template)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='bmasia_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='bmasia_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='bmasia_contact_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_service_items',
            field=models.JSONField(blank=True, default=list, help_text='Custom service items: [{"name": "...", "description": "..."}]'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_contact_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_custom',
            field=models.TextField(blank=True, help_text='Custom payment terms (overrides template)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='preamble_custom',
            field=models.TextField(blank=True, help_text='Custom preamble text (overrides template)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price_per_zone',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per zone per year', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='show_zone_pricing_detail',
            field=models.BooleanField(default=True, help_text='Show per-zone pricing in PDF'),
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('generated', 'System Generated PDF'), ('principal_terms', 'Principal Terms'), ('attachment_a', 'Attachment A - Scope of Work'), ('exhibit_d', 'Exhibit D - Legal Terms'), ('master_agreement', 'Master Agreement'), ('participation_agreement', 'Participation Agreement'), ('standard_terms', 'Standard Terms & Conditions'), ('insurance', 'Insurance Certificate'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='contract_documents/%Y/%m/')),
                ('is_official', models.BooleanField(default=False, help_text='Mark as official signing version')),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_documents', to='crm_app.contract')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Document',
                'verbose_name_plural': 'Contract Documents',
                'ordering': ['-is_official', 'document_type', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='activation_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'template_type': 'activation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_activation', to='crm_app.contracttemplate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_payment', to='crm_app.contracttemplate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='preamble_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'template_type': 'preamble'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_preamble', to='crm_app.contracttemplate'),
        ),
        migrations.CreateModel(
            name='CorporatePdfTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_format', models.CharField(choices=[('standard', 'Standard BMAsia Format'), ('hilton_hpa', 'Hilton HPA Format'), ('marriott', 'Marriott Format'), ('ihg', 'IHG Format'), ('accor', 'Accor Format'), ('custom', 'Custom Format')], default='standard', max_length=30)),
                ('include_exhibit_d', models.BooleanField(default=False, help_text='Generate legal terms exhibit')),
                ('include_attachment_a', models.BooleanField(default=True, help_text='Generate scope of work')),
                ('header_text', models.TextField(blank=True, help_text='Custom header/preamble for this corporate')),
                ('legal_terms', models.TextField(blank=True, help_text='Corporate-specific legal clauses')),
                ('warranty_text', models.TextField(blank=True, help_text='Warranty section text')),
                ('use_corporate_branding', models.BooleanField(default=False)),
                ('corporate_logo', models.ImageField(blank=True, null=True, upload_to='corporate_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(limit_choices_to={'is_corporate_parent': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_template', to='crm_app.company')),
            ],
            options={
                'verbose_name': 'Corporate PDF Template',
                'verbose_name_plural': 'Corporate PDF Templates',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='service_items',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='crm_app.servicepackageitem'),
        ),
    ]
