# Generated by Django migrations

from django.db import migrations


SERVICE_ITEMS = [
    {
        'name': 'Playlist Design & Scheduling',
        'description': 'Assistance to design playlists and schedules on the SYB platform',
        'display_order': 1,
    },
    {
        'name': 'Remote Activation Assistance',
        'description': 'Remote on-line activation assistance',
        'display_order': 2,
    },
    {
        'name': 'Monthly Music Refresh',
        'description': 'Monthly refresh of music content',
        'display_order': 3,
    },
    {
        'name': 'Special Event Playlists',
        'description': 'Special event playlists as needed',
        'display_order': 4,
    },
    {
        'name': 'First Line Technical Support',
        'description': 'First Line Technical Support',
        'display_order': 5,
    },
    {
        'name': '24/7 Back Office Support',
        'description': '24/7 Back Office Online Technical Support',
        'display_order': 6,
    },
    {
        'name': 'Quarterly Music Refresh',
        'description': 'Quarterly music refresh for the term of service',
        'display_order': 7,
    },
    {
        'name': 'Free Music Change Request',
        'description': 'Free music change request for 4 weeks after purchase',
        'display_order': 8,
    },
    {
        'name': 'Free Online Installation',
        'description': 'Free online install; Onsite install free labour up to 2 days',
        'display_order': 9,
    },
    {
        'name': 'Unlimited Festival Events',
        'description': 'Unlimited Festival or special event change of music per year',
        'display_order': 10,
    },
]


TEMPLATES = [
    {
        'name': 'Standard Preamble - Thailand/HK',
        'template_type': 'preamble',
        'content': '''This agreement is made the {{start_date}} between:

BMAsia (Thailand) Co., Ltd. with registered address at 725 S-Metro Building, Suite 144, Level 20, Sukhumvit Road, Klongtan Nuea, Watthana, Bangkok 10110, Thailand (BMA)

and

{{company_legal_name}}, with registered address at {{company_address}} (Client)

(Together "The Parties")

Whereas BMA is a certified legally reseller of Soundtrack Your Brand (SYB) and the Client wishes to subscribe to use background music service platform of SYB under this agreement as follows.''',
        'is_default': True,
        'version': '2025.1',
    },
    {
        'name': 'Standard Preamble - International',
        'template_type': 'preamble',
        'content': '''This agreement is made the {{start_date}} between:

BMAsia Limited with registered address at 22nd Floor, Tai Yau Building, 181 Johnston Road, Wan Chai, Hong Kong (BMA)

and

{{company_legal_name}}, with registered address at {{company_address}} (Client)

(Together "The Parties")

Whereas BMA is a certified legally reseller of Soundtrack Your Brand (SYB) and the Client wishes to subscribe to use background music service platform of SYB under this agreement as follows.''',
        'is_default': False,
        'version': '2025.1',
    },
    {
        'name': 'Payment Terms - Thailand',
        'template_type': 'payment_thailand',
        'content': '''Terms of payment: by bank transfer on a net received paid in full, less withholding tax, to BMA's bank account TMBThanachart bank, Thonglor Soi 17 branch, Bangkok due immediately on invoicing to activate access to the SYB platform. All outbound and inbound bank transfer fees are borne by the client in remitting payments as invoiced.''',
        'is_default': True,
        'version': '2025.1',
    },
    {
        'name': 'Payment Terms - International',
        'template_type': 'payment_international',
        'content': '''Terms of payment: by bank transfer on a net received paid in full basis to BMA's bank account HSBC Hong Kong, account number 808-021570-838, SWIFT code HSBCHKHHHKH, due within 30 days of invoicing. All outbound and inbound bank transfer fees are borne by the client in remitting payments as invoiced.''',
        'is_default': False,
        'version': '2025.1',
    },
    {
        'name': 'Standard Activation Terms',
        'template_type': 'activation',
        'content': '''Activation Date: within 1 day of confirming receipt of full payment.''',
        'is_default': True,
        'version': '2025.1',
    },
]


def create_default_data(apps, schema_editor):
    ContractTemplate = apps.get_model('crm_app', 'ContractTemplate')
    ServicePackageItem = apps.get_model('crm_app', 'ServicePackageItem')

    # Create service items
    for item_data in SERVICE_ITEMS:
        ServicePackageItem.objects.get_or_create(
            name=item_data['name'],
            defaults={
                'description': item_data['description'],
                'display_order': item_data['display_order'],
                'is_standard': True,
            }
        )

    # Create templates
    for template_data in TEMPLATES:
        ContractTemplate.objects.get_or_create(
            name=template_data['name'],
            defaults={
                'template_type': template_data['template_type'],
                'content': template_data['content'],
                'is_default': template_data['is_default'],
                'version': template_data['version'],
                'is_active': True,
            }
        )


def reverse_data(apps, schema_editor):
    # Don't delete on reverse - data might have been modified
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0041_contract_content_management'),
    ]

    operations = [
        migrations.RunPython(create_default_data, reverse_data),
    ]
