# Generated by Django 5.2.2 on 2026-01-04 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0042_seed_contract_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='seasonal_emails_enabled',
            field=models.BooleanField(default=True, help_text='Receive seasonal/holiday email campaigns (Christmas, CNY, Songkran, etc.)'),
        ),
        migrations.AlterField(
            model_name='emailsequence',
            name='sequence_type',
            field=models.CharField(choices=[('manual', 'Manual Enrollment'), ('auto_renewal', 'Auto: Contract Renewal'), ('auto_payment', 'Auto: Payment Reminders'), ('auto_quarterly', 'Auto: Quarterly Check-ins'), ('auto_seasonal_christmas', 'Auto: Christmas (All)'), ('auto_seasonal_cny', 'Auto: Chinese New Year (Asia)'), ('auto_seasonal_songkran', 'Auto: Songkran (Thailand)'), ('auto_seasonal_loy_krathong', 'Auto: Loy Krathong (Thailand)'), ('auto_seasonal_valentines', 'Auto: Valentines Day (All)'), ('auto_seasonal_ramadan', 'Auto: Ramadan (Middle East)'), ('auto_seasonal_singapore_nd', 'Auto: Singapore National Day')], default='manual', help_text='Type of automation - manual requires enrollment, auto types trigger automatically', max_length=30),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('renewal_30_days', '30-Day Renewal Reminder'), ('renewal_14_days', '14-Day Renewal Reminder'), ('renewal_7_days', '7-Day Renewal Reminder'), ('renewal_urgent', 'Urgent Renewal Notice'), ('invoice_new', 'New Invoice'), ('payment_reminder_7_days', '7-Day Payment Reminder'), ('payment_reminder_14_days', '14-Day Payment Reminder'), ('payment_overdue', 'Payment Overdue Notice'), ('quarterly_checkin', 'Quarterly Check-in'), ('seasonal_christmas', 'Christmas Season Preparation'), ('seasonal_newyear', 'Chinese New Year Preparation'), ('seasonal_valentines', "Valentine's Day Preparation"), ('seasonal_songkran', 'Songkran Preparation'), ('seasonal_loy_krathong', 'Loy Krathong Preparation'), ('seasonal_ramadan', 'Ramadan Preparation'), ('seasonal_singapore_national_day', 'Singapore National Day Preparation'), ('zone_offline_48h', 'Zone Offline 48 Hours'), ('zone_offline_7d', 'Zone Offline 7 Days'), ('welcome', 'Welcome Email'), ('contract_signed', 'Contract Signed Confirmation')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SeasonalTriggerDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holiday_type', models.CharField(choices=[('auto_seasonal_cny', 'Chinese New Year'), ('auto_seasonal_ramadan', 'Ramadan'), ('auto_seasonal_loy_krathong', 'Loy Krathong')], help_text='Which holiday this trigger date is for', max_length=50)),
                ('trigger_date', models.DateField(help_text='Date to send campaign emails (typically 2 weeks before the holiday)')),
                ('year', models.IntegerField(help_text='Year this trigger date applies to')),
                ('holiday_date', models.DateField(blank=True, help_text='Actual holiday date (for reference)', null=True)),
                ('notes', models.TextField(blank=True, help_text="Any notes about this year's campaign")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonal_trigger_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seasonal Trigger Date',
                'verbose_name_plural': 'Seasonal Trigger Dates',
                'ordering': ['-year', 'trigger_date'],
                'unique_together': {('holiday_type', 'year')},
            },
        ),
    ]
