# Generated by Django 5.2.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0043_seasonal_automation_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='receives_renewal_emails',
            field=models.BooleanField(default=True, help_text='Receives contract renewal reminders'),
        ),
        migrations.AddField(
            model_name='contact',
            name='receives_seasonal_emails',
            field=models.BooleanField(default=True, help_text='Receives seasonal/holiday campaign emails'),
        ),
        migrations.AddField(
            model_name='contact',
            name='receives_payment_emails',
            field=models.BooleanField(default=True, help_text='Receives payment reminder emails'),
        ),
        migrations.AddField(
            model_name='contact',
            name='receives_quarterly_emails',
            field=models.BooleanField(default=True, help_text='Receives quarterly check-in emails'),
        ),
    ]
