# Generated by Django 5.2.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0044_contact_email_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='send_renewal_reminders',
            field=models.BooleanField(default=True, help_text='Send automatic renewal reminder emails for this contract'),
        ),
    ]
