# Generated by Django 5.2.2 on 2026-01-06 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0045_contract_send_renewal_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='soundtrack_offline_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Send email alerts when music zones go offline'),
        ),
        migrations.AddField(
            model_name='contact',
            name='receives_soundtrack_alerts',
            field=models.BooleanField(default=False, help_text='Receives alerts when music zones go offline'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='receives_notifications',
            field=models.BooleanField(default=True, help_text='Master switch: receives any automated emails'),
        ),
        migrations.AlterField(
            model_name='emailsequence',
            name='sequence_type',
            field=models.CharField(choices=[('manual', 'Manual Enrollment'), ('auto_renewal', 'Auto: Contract Renewal'), ('auto_payment', 'Auto: Payment Reminders'), ('auto_quarterly', 'Auto: Quarterly Check-ins'), ('auto_seasonal_christmas', 'Auto: Christmas (All)'), ('auto_seasonal_valentines', 'Auto: Valentines Day (All)'), ('auto_seasonal_songkran', 'Auto: Songkran (Thailand)'), ('auto_seasonal_singapore_nd', 'Auto: Singapore National Day'), ('auto_seasonal_cny', 'Auto: Chinese New Year (Asia)'), ('auto_seasonal_loy_krathong', 'Auto: Loy Krathong (Thailand)'), ('auto_seasonal_ramadan', 'Auto: Ramadan (Middle East)'), ('auto_seasonal_diwali', 'Auto: Diwali (India/SE Asia)'), ('auto_seasonal_mid_autumn', 'Auto: Mid-Autumn Festival (Asia)'), ('auto_seasonal_eid_fitr', 'Auto: Eid al-Fitr (Indonesia/Malaysia)')], default='manual', help_text='Type of automation - manual requires enrollment, auto types trigger automatically', max_length=30),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('renewal_30_days', '30-Day Renewal Reminder'), ('renewal_14_days', '14-Day Renewal Reminder'), ('renewal_7_days', '7-Day Renewal Reminder'), ('renewal_urgent', 'Urgent Renewal Notice'), ('invoice_new', 'New Invoice'), ('payment_reminder_7_days', '7-Day Payment Reminder'), ('payment_reminder_14_days', '14-Day Payment Reminder'), ('payment_overdue', 'Payment Overdue Notice'), ('quarterly_checkin', 'Quarterly Check-in'), ('seasonal_christmas', 'Christmas Season Preparation'), ('seasonal_newyear', 'Chinese New Year Preparation'), ('seasonal_valentines', "Valentine's Day Preparation"), ('seasonal_songkran', 'Songkran Preparation'), ('seasonal_loy_krathong', 'Loy Krathong Preparation'), ('seasonal_ramadan', 'Ramadan Preparation'), ('seasonal_singapore_national_day', 'Singapore National Day Preparation'), ('seasonal_diwali', 'Diwali Preparation'), ('seasonal_mid_autumn', 'Mid-Autumn Festival Preparation'), ('seasonal_eid_fitr', 'Eid al-Fitr Preparation'), ('zone_offline_alert', 'Zone Offline Alert (Auto)'), ('zone_offline_48h', 'Zone Offline 48 Hours'), ('zone_offline_7d', 'Zone Offline 7 Days'), ('welcome', 'Welcome Email'), ('contract_signed', 'Contract Signed Confirmation')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='seasonaltriggerdate',
            name='holiday_type',
            field=models.CharField(choices=[('auto_seasonal_cny', 'Chinese New Year'), ('auto_seasonal_ramadan', 'Ramadan'), ('auto_seasonal_loy_krathong', 'Loy Krathong'), ('auto_seasonal_diwali', 'Diwali'), ('auto_seasonal_mid_autumn', 'Mid-Autumn Festival'), ('auto_seasonal_eid_fitr', 'Eid al-Fitr')], help_text='Which holiday this trigger date is for', max_length=50),
        ),
        migrations.CreateModel(
            name='ZoneOfflineAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_at', models.DateTimeField(help_text='When zone first went offline')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When zone came back online', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('first_notification_sent', models.BooleanField(default=False)),
                ('first_notification_at', models.DateTimeField(blank=True, null=True)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.IntegerField(default=0)),
                ('notified_contacts', models.ManyToManyField(blank=True, related_name='offline_alert_notifications', to='crm_app.contact')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_alerts', to='crm_app.zone')),
            ],
            options={
                'verbose_name': 'Zone Offline Alert',
                'verbose_name_plural': 'Zone Offline Alerts',
                'ordering': ['-detected_at'],
            },
        ),
    ]
