# Generated by Django 5.2.2 on 2026-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0046_soundtrack_offline_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='soundtrack_account_id',
            field=models.CharField(blank=True, help_text="Soundtrack account ID for this contract (overrides company's)", max_length=100),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_orphaned',
            field=models.BooleanField(default=False, help_text='Zone exists in CRM but not found in Soundtrack API'),
        ),
        migrations.AddField(
            model_name='zone',
            name='orphaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
