# Generated by Django 5.2.2 on 2026-01-13 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0047_zone_management_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRevenueEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('new_contract', 'New Contract Signed'), ('renewal', 'Contract Renewed'), ('addon_zones', 'Zones Added'), ('removal_zones', 'Zones Removed'), ('value_increase', 'Value Increased'), ('value_decrease', 'Value Decreased'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('churn', 'Contract Churned/Canceled'), ('reactivation', 'Contract Reactivated')], help_text='Type of revenue event', max_length=30)),
                ('event_date', models.DateField(help_text='Date when this event occurred')),
                ('contract_value_change', models.DecimalField(decimal_places=2, default=0, help_text='Change in total contract value (positive or negative)', max_digits=12)),
                ('monthly_value_change', models.DecimalField(decimal_places=2, default=0, help_text='Change in monthly recurring value', max_digits=12)),
                ('zone_count_change', models.IntegerField(default=0, help_text='Change in number of zones (positive or negative)')),
                ('expected_payment_date', models.DateField(blank=True, help_text='When payment was expected', null=True)),
                ('actual_payment_date', models.DateField(blank=True, help_text='When payment was actually received', null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of payment received', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional details about this event')),
            ],
            options={
                'verbose_name': 'Contract Revenue Event',
                'verbose_name_plural': 'Contract Revenue Events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRevenueSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year of the snapshot (e.g., 2026)')),
                ('month', models.IntegerField(help_text='Month of the snapshot (1-12)')),
                ('category', models.CharField(choices=[('new', 'New Contract'), ('renewal', 'Renewal'), ('addon', 'Add-on (Zone Addition)'), ('churn', 'Canceled/Churned')], help_text='Revenue category (new/renewal/addon/churn)', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('THB', 'THB - Thai Baht'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound')], default='USD', help_text='Currency for this snapshot', max_length=3)),
                ('billing_entity', models.CharField(choices=[('bmasia_hk', 'BMAsia Limited (Hong Kong)'), ('bmasia_th', 'BMAsia (Thailand) Co., Ltd.')], help_text='Which BMAsia entity is billing', max_length=20)),
                ('contract_count', models.IntegerField(default=0, help_text='Number of contracts in this category for the month')),
                ('contracted_value', models.DecimalField(decimal_places=2, default=0, help_text='Total contract value for this category', max_digits=15)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, help_text='Actual cash received in this period', max_digits=15)),
                ('is_manually_overridden', models.BooleanField(default=False, help_text="If true, values were manually entered and won't be auto-calculated")),
                ('override_reason', models.TextField(blank=True, help_text='Reason for manual override')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this snapshot')),
            ],
            options={
                'verbose_name': 'Monthly Revenue Snapshot',
                'verbose_name_plural': 'Monthly Revenue Snapshots',
                'ordering': ['-year', '-month', 'category'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRevenueTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Target year (e.g., 2026)')),
                ('month', models.IntegerField(help_text='Target month (1-12)')),
                ('category', models.CharField(choices=[('new', 'New Contract'), ('renewal', 'Renewal'), ('addon', 'Add-on (Zone Addition)'), ('churn', 'Canceled/Churned')], help_text='Revenue category for this target', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('THB', 'THB - Thai Baht'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound')], default='USD', help_text='Currency for this target', max_length=3)),
                ('billing_entity', models.CharField(choices=[('bmasia_hk', 'BMAsia Limited (Hong Kong)'), ('bmasia_th', 'BMAsia (Thailand) Co., Ltd.')], help_text='Which BMAsia entity this target applies to', max_length=20)),
                ('target_contract_count', models.IntegerField(default=0, help_text='Target number of contracts for this category')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Target contracted revenue', max_digits=15)),
                ('target_cash_flow', models.DecimalField(decimal_places=2, default=0, help_text='Target cash collection', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Notes about this target or assumptions')),
            ],
            options={
                'verbose_name': 'Monthly Revenue Target',
                'verbose_name_plural': 'Monthly Revenue Targets',
                'ordering': ['-year', '-month', 'category'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='lifecycle_effective_date',
            field=models.DateField(blank=True, help_text='Date when this lifecycle type became effective', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='lifecycle_type',
            field=models.CharField(blank=True, choices=[('new', 'New Contract'), ('renewal', 'Renewal'), ('addon', 'Add-on (Zone Addition)'), ('churn', 'Canceled/Churned')], help_text='Revenue type classification for finance tracking', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='lifecycle_type_manually_set',
            field=models.BooleanField(default=False, help_text="If true, lifecycle_type was manually set and won't be auto-updated"),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['lifecycle_type', 'lifecycle_effective_date'], name='crm_app_con_lifecyc_713f92_idx'),
        ),
        migrations.AddField(
            model_name='contractrevenueevent',
            name='contract',
            field=models.ForeignKey(help_text='Contract associated with this event', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_events', to='crm_app.contract'),
        ),
        migrations.AddField(
            model_name='contractrevenueevent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who logged this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_revenue_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenuesnapshot',
            index=models.Index(fields=['year', 'month'], name='crm_app_mon_year_46f52b_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenuesnapshot',
            index=models.Index(fields=['category', 'year', 'month'], name='crm_app_mon_categor_81d451_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenuesnapshot',
            index=models.Index(fields=['billing_entity', 'year', 'month'], name='crm_app_mon_billing_fd5487_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenuesnapshot',
            index=models.Index(fields=['currency', 'year', 'month'], name='crm_app_mon_currenc_152f51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrevenuesnapshot',
            unique_together={('year', 'month', 'category', 'currency', 'billing_entity')},
        ),
        migrations.AddField(
            model_name='monthlyrevenuetarget',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who set this target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contractrevenueevent',
            index=models.Index(fields=['contract', 'event_date'], name='crm_app_con_contrac_bf5a91_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrevenueevent',
            index=models.Index(fields=['event_type', 'event_date'], name='crm_app_con_event_t_f9fbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrevenueevent',
            index=models.Index(fields=['event_date'], name='crm_app_con_event_d_122d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrevenueevent',
            index=models.Index(fields=['contract', 'event_type'], name='crm_app_con_contrac_c4a8be_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenuetarget',
            index=models.Index(fields=['year', 'month'], name='crm_app_mon_year_50ad60_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenuetarget',
            index=models.Index(fields=['category', 'year', 'month'], name='crm_app_mon_categor_76ade6_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenuetarget',
            index=models.Index(fields=['billing_entity', 'year', 'month'], name='crm_app_mon_billing_2c83b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrevenuetarget',
            unique_together={('year', 'month', 'category', 'currency', 'billing_entity')},
        ),
    ]
