# Generated by Django 5.2.2 on 2026-01-13 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0049_expense_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year (e.g., 2026)')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('billing_entity', models.CharField(choices=[('bmasia_th', 'BMAsia (Thailand) Co., Ltd.'), ('bmasia_hk', 'BMAsia Limited')], help_text='Which BMAsia entity this applies to', max_length=20)),
                ('currency', models.CharField(choices=[('THB', 'Thai Baht'), ('USD', 'US Dollar')], default='THB', max_length=3)),
                ('opening_cash_balance', models.DecimalField(decimal_places=2, default=0, help_text='Cash balance at start of period', max_digits=15)),
                ('cash_from_customers', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Cash received from customer invoice payments', max_digits=15, null=True)),
                ('cash_to_suppliers', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Cash paid to suppliers (non-salary OpEx)', max_digits=15, null=True)),
                ('cash_to_employees', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Cash paid for salaries/payroll', max_digits=15, null=True)),
                ('other_operating_cash', models.DecimalField(decimal_places=2, default=0, help_text='Other operating cash flows (manual entry)', max_digits=15)),
                ('capex_purchases', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Cash paid for capital expenditures', max_digits=15, null=True)),
                ('asset_sales', models.DecimalField(decimal_places=2, default=0, help_text='Cash received from asset sales', max_digits=15)),
                ('other_investing_cash', models.DecimalField(decimal_places=2, default=0, help_text='Other investing cash flows', max_digits=15)),
                ('loan_proceeds', models.DecimalField(decimal_places=2, default=0, help_text='Cash received from new loans', max_digits=15)),
                ('loan_repayments', models.DecimalField(decimal_places=2, default=0, help_text='Cash paid to repay loans', max_digits=15)),
                ('equity_injections', models.DecimalField(decimal_places=2, default=0, help_text='Cash received from equity investments', max_digits=15)),
                ('dividends_paid', models.DecimalField(decimal_places=2, default=0, help_text='Cash paid as dividends', max_digits=15)),
                ('other_financing_cash', models.DecimalField(decimal_places=2, default=0, help_text='Other financing cash flows', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Notes about this period')),
                ('is_finalized', models.BooleanField(default=False, help_text='Mark as finalized to prevent auto-recalculation')),
            ],
            options={
                'verbose_name': 'Cash Flow Snapshot',
                'verbose_name_plural': 'Cash Flow Snapshots',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='crm_app_exp_categor_abb2d2_idx',
            old_name='crm_app_exp_cat_typ_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='crm_app_exp_parent__0ffd71_idx',
            old_name='crm_app_exp_parent_j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_categor_c3cea5_idx',
            old_name='crm_app_exp_cat_y5z6a7_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_vendor__7f5222_idx',
            old_name='crm_app_exp_vendor_b8c9d0_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_billing_24813b_idx',
            old_name='crm_app_exp_billing_e1f2g3_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_expense_6525c3_idx',
            old_name='crm_app_exp_exp_dat_h4i5j6_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_due_dat_93e57f_idx',
            old_name='crm_app_exp_due_dat_k7l8m9_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_status_e60b79_idx',
            old_name='crm_app_exp_status_n0o1p2_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_payment_5f369d_idx',
            old_name='crm_app_exp_pay_dat_q3r4s5_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseentry',
            new_name='crm_app_exp_expense_ffb185_idx',
            old_name='crm_app_exp_exp_bil_t6u7v8_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringexpense',
            new_name='crm_app_rec_categor_3ea1de_idx',
            old_name='crm_app_rec_cat_m3n4o5_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringexpense',
            new_name='crm_app_rec_billing_6cf8f0_idx',
            old_name='crm_app_rec_billing_p6q7r8_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringexpense',
            new_name='crm_app_rec_is_acti_d85f1d_idx',
            old_name='crm_app_rec_is_acti_s9t0u1_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringexpense',
            new_name='crm_app_rec_start_d_7fc203_idx',
            old_name='crm_app_rec_start_v2w3x4_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='crm_app_ven_name_aa8318_idx',
            old_name='crm_app_ven_name_8b1234_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='crm_app_ven_billing_3e644e_idx',
            old_name='crm_app_ven_billing_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='crm_app_ven_is_acti_21b981_idx',
            old_name='crm_app_ven_is_acti_d4e5f6_idx',
        ),
        migrations.AddField(
            model_name='cashflowsnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cashflowsnapshot',
            index=models.Index(fields=['year', 'month'], name='crm_app_cas_year_651f69_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowsnapshot',
            index=models.Index(fields=['billing_entity', 'year', 'month'], name='crm_app_cas_billing_ae35fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashflowsnapshot',
            unique_together={('year', 'month', 'billing_entity', 'currency')},
        ),
    ]
