# Generated by Django 5.2.2 on 2026-01-13 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0050_cash_flow_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year (e.g., 2026)')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (Jan-Mar)'), (2, 'Q2 (Apr-Jun)'), (3, 'Q3 (Jul-Sep)'), (4, 'Q4 (Oct-Dec)')], help_text='Quarter (1-4)')),
                ('billing_entity', models.CharField(choices=[('bmasia_th', 'BMAsia (Thailand) Co., Ltd.'), ('bmasia_hk', 'BMAsia Limited')], help_text='Which BMAsia entity this applies to', max_length=20)),
                ('currency', models.CharField(choices=[('THB', 'Thai Baht'), ('USD', 'US Dollar')], default='THB', max_length=3)),
                ('cash_and_bank', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Cash and bank balances (from CashFlowSnapshot closing balance)', max_digits=15, null=True)),
                ('accounts_receivable', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Outstanding customer invoices (Sent + Overdue)', max_digits=15, null=True)),
                ('other_current_assets', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Prepaid expenses, deposits, etc.', max_digits=15)),
                ('gross_fixed_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Total CapEx purchases (computer equipment, office equipment)', max_digits=15, null=True)),
                ('accumulated_depreciation', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Total accumulated depreciation', max_digits=15, null=True)),
                ('accounts_payable', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Outstanding vendor payments (pending + approved expenses)', max_digits=15, null=True)),
                ('accrued_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Accrued salaries, taxes, etc.', max_digits=15)),
                ('other_current_liabilities', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Short-term portions of loans, etc.', max_digits=15)),
                ('long_term_debt', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Long-term loans and borrowings', max_digits=15)),
                ('other_long_term_liabilities', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Deferred tax liabilities, etc.', max_digits=15)),
                ('share_capital', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Issued share capital', max_digits=15)),
                ('additional_paid_in_capital', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Share premium / APIC', max_digits=15)),
                ('retained_earnings', models.DecimalField(blank=True, decimal_places=2, help_text='Override: Cumulative net profit (calculated from P&L)', max_digits=15, null=True)),
                ('other_equity', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Other reserves, adjustments', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Notes about this period')),
                ('is_finalized', models.BooleanField(default=False, help_text='Mark as finalized to prevent auto-recalculation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheet_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance Sheet Snapshot',
                'verbose_name_plural': 'Balance Sheet Snapshots',
                'ordering': ['-year', '-quarter'],
                'indexes': [models.Index(fields=['year', 'quarter'], name='crm_app_bal_year_044698_idx'), models.Index(fields=['billing_entity', 'year', 'quarter'], name='crm_app_bal_billing_b09da3_idx')],
                'unique_together': {('year', 'quarter', 'billing_entity', 'currency')},
            },
        ),
    ]
